
import java.io.File;
import java.sql.*;
import java.util.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Work
 */
public class AdminParentFrm extends javax.swing.JFrame {
    private File f;
    
    /**
     * Creates new form ParentsFrm
     */
    public AdminParentFrm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        edtName = new java.awt.TextField();
        edtSname = new java.awt.TextField();
        edtContact = new java.awt.TextField();
        spnChildren = new javax.swing.JSpinner();
        btnSubmit = new javax.swing.JButton();
        edtAddress = new java.awt.TextField();
        btnCancel = new javax.swing.JButton();
        proBar = new javax.swing.JProgressBar();
        edtID_Passport = new javax.swing.JTextField();
        btnCitizen = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Add Parent");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Parent Details");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 20, -1, -1));

        jLabel2.setText("First name(s):");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 60, -1, -1));

        jLabel3.setText("Surname:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 90, -1, -1));

        jLabel4.setText("Contract Number:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 120, -1, -1));

        jLabel5.setText("Address");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 150, -1, -1));

        jLabel6.setText("Number of children enrolled:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 180, -1, -1));
        getContentPane().add(edtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(205, 56, 130, -1));
        getContentPane().add(edtSname, new org.netbeans.lib.awtextra.AbsoluteConstraints(205, 86, 130, -1));
        getContentPane().add(edtContact, new org.netbeans.lib.awtextra.AbsoluteConstraints(205, 116, 130, -1));

        spnChildren.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));
        getContentPane().add(spnChildren, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 180, 38, -1));

        btnSubmit.setText("Submit");
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitActionPerformed(evt);
            }
        });
        getContentPane().add(btnSubmit, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 300, 93, -1));
        getContentPane().add(edtAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(205, 146, 130, -1));

        btnCancel.setText("Cancel");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });
        getContentPane().add(btnCancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 300, 93, -1));
        getContentPane().add(proBar, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 270, -1, -1));
        getContentPane().add(edtID_Passport, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 230, 130, -1));

        btnCitizen.setText("Upload ID/Passport");
        btnCitizen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCitizenActionPerformed(evt);
            }
        });
        getContentPane().add(btnCitizen, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 230, -1, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Used_chalk_board.jpg"))); // NOI18N
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 380, 340));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed
        boolean valid = true;
        
        //setting name
        String name = edtName.getText();
        if (name.equals(""))
        {
            JOptionPane.showMessageDialog(null, "First name(s) is empty");
            valid = false;
        } else {
            proBar.setValue(proBar.getValue() + 20);
        }
        
        //setting surname
        String sname = edtSname.getText();
        if (sname.equals(""))
        {
            JOptionPane.showMessageDialog(null, "Surname is empty");
            valid = false;
        } else {
            proBar.setValue(proBar.getValue() + 20);
        }
        
        //setting the contact number
        String cont = edtContact.getText();
        if (cont.length() != 10)
        {
            System.out.println("Contact number is invalid");
            valid = false;
        }
        else
        {
            for (int i = 0; i < 10; i++) 
            {
              if (!Character.isDigit(cont.charAt(i))) 
              {
                  valid = false;
              } else {
                proBar.setValue(proBar.getValue() + 2);
              }                
            }
        }
        
        //setting home address
        String address = edtAddress.getText();
        if (address.equals(""))
        {
            JOptionPane.showMessageDialog(null, "Please enter your address");
            valid = false;
        } else {
            proBar.setValue(proBar.getValue() + 20);
        }
        
        //setting the number of childern enrolled in the school
        int children = (int) spnChildren.getValue();        
        proBar.setValue(proBar.getValue() + 20);
        
        //setting the file to the correct format
        String filename = edtID_Passport.getText();
        if (address.equals(""))
        {
            JOptionPane.showMessageDialog(null, "Please upload a copy of your ID / passport");
            valid = false;
        } else {
            proBar.setValue(proBar.getValue() + 20);
        }
                
        //setting password 
        int num = (int) Math.round(Math.random()*100);
        String chara = "!@#$^&";
        Random random = new Random();
        int index = random.nextInt(chara.length());        
        String pswd = (sname + name.charAt(0)).toLowerCase() + Integer.toString(num) + chara.charAt(index);
        
        //if everything is valid, try to save it in the database
        if (valid)
        {
            try {          
                Main pro = new Main();
                pro.createConnection();
                
                String sql = "INSERT INTO tblparent(`Name`, `Surname`, `ContactNumber`, `Address`, `NumberEnrolled`, `IDdoc`, `Password`) values (?, ?, ?, ?, ?, ?, ?)";
                PreparedStatement pstmt = Main.con.prepareStatement(sql);
                pstmt.setString(1, name);
                pstmt.setString(2, sname);
                pstmt.setString(3, cont);
                pstmt.setString(4, address);
                pstmt.setInt(5, children);
                pstmt.setBlob(6, (Blob) f);
                pstmt.setString(7, pswd);
                
                pstmt.executeUpdate();
                JOptionPane.showMessageDialog(null, "Parents details successfully recorded");
                
                new AdminDashboard().setVisible(true);
                dispose();
                
                Main.con.close();
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, ex);
            }
            
            try {          
                Main pro = new Main();
                pro.createConnection();
                
                while (children > 0)
                {
                    int stuID = Integer.parseInt(JOptionPane.showInputDialog(null, "Enter child's ID"));
                    children--;
                    
                    Statement Pstmt = (Statement) Main.con.createStatement();
                    String Psql = "SELECT ParentID FROM tblparent WHERE (ContactNumber LIKE '" + cont + "')";
                    ResultSet Prs = Pstmt.executeQuery(Psql);
                    Prs.beforeFirst();

                    int parID = 0;
                    while (Prs.next()) {
                        parID = Prs.getInt("ParentID");
                    }
                    
                    Statement stmt = (Statement) Main.con.createStatement();
                    String sql = "INSERT INTO parent_student (FK_parentID, FK_studentID) VALUES ("+parID+", "+stuID+")";
                    stmt.execute(sql);
                }
                
                Main.con.close();
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, ex);
            }
        }
    }//GEN-LAST:event_btnSubmitActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        try {
            new AdminDashboard().setVisible(true);
            dispose();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_btnCancelActionPerformed

    private void btnCitizenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCitizenActionPerformed
        JFileChooser chooser = new JFileChooser();
        chooser.showOpenDialog(null);
        f = chooser.getSelectedFile();
        String filename = f.getAbsolutePath();
        edtID_Passport.setText(filename);
    }//GEN-LAST:event_btnCitizenActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnCitizen;
    private javax.swing.JButton btnSubmit;
    private java.awt.TextField edtAddress;
    private java.awt.TextField edtContact;
    private javax.swing.JTextField edtID_Passport;
    private java.awt.TextField edtName;
    private java.awt.TextField edtSname;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JProgressBar proBar;
    private javax.swing.JSpinner spnChildren;
    // End of variables declaration//GEN-END:variables
}
