
import java.io.File;
import java.util.Date;
import javax.swing.JOptionPane;
import java.sql.*;
import java.text.SimpleDateFormat;
import java.util.Random;
import javax.swing.JFileChooser;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Work
 */
public class AdminStudentFrm extends javax.swing.JFrame {
    private File fID ;
    private File fProof;
    
    /**
     * Creates new form StudentsFrm
     */
    public AdminStudentFrm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        edtName = new java.awt.TextField();
        edtSname = new java.awt.TextField();
        dDob = new org.jdesktop.swingx.JXDatePicker();
        ckbMale = new javax.swing.JCheckBox();
        ckbFemale = new javax.swing.JCheckBox();
        spnGrade = new javax.swing.JSpinner();
        btnSubmit = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        proBar = new javax.swing.JProgressBar();
        edtID_Passport = new javax.swing.JTextField();
        edtProof = new javax.swing.JTextField();
        btnID_Password = new javax.swing.JButton();
        btnProof = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Add Student");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Student Details");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 10, -1, -1));

        jLabel2.setText("First name(s):");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 60, -1, -1));

        jLabel3.setText("Surname:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 100, -1, -1));

        jLabel4.setText("Date of birth:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 140, -1, -1));

        jLabel5.setText("Grade:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 220, -1, -1));
        getContentPane().add(edtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(199, 56, 130, -1));
        getContentPane().add(edtSname, new org.netbeans.lib.awtextra.AbsoluteConstraints(199, 96, 130, -1));
        getContentPane().add(dDob, new org.netbeans.lib.awtextra.AbsoluteConstraints(199, 139, 130, -1));

        ckbMale.setText("Male");
        ckbMale.setContentAreaFilled(false);
        ckbMale.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                ckbMaleStateChanged(evt);
            }
        });
        getContentPane().add(ckbMale, new org.netbeans.lib.awtextra.AbsoluteConstraints(124, 179, -1, -1));

        ckbFemale.setText("Female");
        ckbFemale.setContentAreaFilled(false);
        ckbFemale.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                ckbFemaleStateChanged(evt);
            }
        });
        getContentPane().add(ckbFemale, new org.netbeans.lib.awtextra.AbsoluteConstraints(199, 179, -1, -1));

        spnGrade.setModel(new javax.swing.SpinnerNumberModel(1, 1, 12, 1));
        getContentPane().add(spnGrade, new org.netbeans.lib.awtextra.AbsoluteConstraints(199, 212, 43, -1));

        btnSubmit.setLabel("Submit");
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitActionPerformed(evt);
            }
        });
        getContentPane().add(btnSubmit, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 390, 93, -1));

        btnCancel.setText("Cancel");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });
        getContentPane().add(btnCancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 390, 93, -1));
        getContentPane().add(proBar, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 350, 154, -1));
        getContentPane().add(edtID_Passport, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, 190, -1));
        getContentPane().add(edtProof, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, 190, -1));

        btnID_Password.setText("Parent ID/Passport");
        btnID_Password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnID_PasswordActionPerformed(evt);
            }
        });
        getContentPane().add(btnID_Password, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 260, 130, -1));

        btnProof.setText("Proof of Gardianship");
        btnProof.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProofActionPerformed(evt);
            }
        });
        getContentPane().add(btnProof, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 300, -1, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Used_chalk_board.jpg"))); // NOI18N
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 480));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed
        boolean valid = true;
        
        //setting name
        String name = edtName.getText();
        if (name.equals(""))
        {
            JOptionPane.showMessageDialog(null, "First name(s) is empty");
            valid = false;
        } else {
            proBar.setValue(proBar.getValue() + 20);
        }
        
        //setting surname
        String sname = edtSname.getText();
        if (sname.equals(""))
        {
            JOptionPane.showMessageDialog(null, "Surname is empty");
            valid = false;
        } else {
            proBar.setValue(proBar.getValue() + 20);
        }
        
        //setting birth date
        Date dob = dDob.getDate();
        SimpleDateFormat dformat = new SimpleDateFormat("yyyy-mm-dd");
        String sDob = dformat.format(dob);
        proBar.setValue(proBar.getValue() + 20);
                
        //setting gender
        char gender = 'O';
        if (ckbMale.isSelected()) {
            gender = 'M';
            proBar.setValue(proBar.getValue() + 20);
        } else if (ckbFemale.isSelected()) {
            gender = 'F';
            proBar.setValue(proBar.getValue() + 20);
        } else {
            JOptionPane.showMessageDialog(null, "Gender not selected");
            valid = false;
        }
        
        //setting grade
        int grade = (int) spnGrade.getValue();
        proBar.setValue(proBar.getValue() + 20);
                
        //setting password 
        int num = (int) Math.round(Math.random()*100);
        String chara = "!@#$^&";
        Random random = new Random();
        int index = random.nextInt(chara.length());        
        String pswd = (sname + name.charAt(0)).toLowerCase() + Integer.toString(num) + chara.charAt(index);
                
        //if everything is valid, try to save it in the database
        if (valid)
        {
            try {
                Main pro = new Main();
                pro.createConnection();
                
                String sql = "INSERT INTO tblstudent(`Name`, `Surname`, `DateOfBirth`, `Gender`, `Grade`, `IDdoc`, `GuardianProof`, `Password`) values (?, ?, ?, ?, ?, ?, ?, ?)";
                PreparedStatement pstmt = Main.con.prepareStatement(sql);
                pstmt.setString(1, name);
                pstmt.setString(2, sname);
                pstmt.setString(3, sDob);
                pstmt.setString(4, Character.toString(gender));
                pstmt.setInt(5, grade);
                pstmt.setBlob(6, (Blob) fID);
                pstmt.setBlob(7, (Blob) fProof);
                pstmt.setString(8, pswd);
                
                pstmt.executeUpdate();
                JOptionPane.showMessageDialog(null, "Student details successfully recorded");
                
                Main.con.close();
                
                new AdminDashboard().setVisible(true);
                dispose();
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, ex);
            }
        }
    }//GEN-LAST:event_btnSubmitActionPerformed

    private void ckbMaleStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_ckbMaleStateChanged
        if (ckbMale.isSelected())
            ckbFemale.setSelected(false);
    }//GEN-LAST:event_ckbMaleStateChanged

    private void ckbFemaleStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_ckbFemaleStateChanged
        if (ckbFemale.isSelected())
            ckbMale.setSelected(false);
    }//GEN-LAST:event_ckbFemaleStateChanged

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        try {
            new AdminDashboard().setVisible(true);
            dispose();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_btnCancelActionPerformed

    private void btnID_PasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnID_PasswordActionPerformed
        JFileChooser chooser = new JFileChooser();
        chooser.showOpenDialog(null);
        fID = chooser.getSelectedFile();
        String filename = fID.getAbsolutePath();
        edtID_Passport.setText(filename);
    }//GEN-LAST:event_btnID_PasswordActionPerformed

    private void btnProofActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProofActionPerformed
        JFileChooser chooser = new JFileChooser();
        chooser.showOpenDialog(null);
        fProof = chooser.getSelectedFile();
        String filename = fProof.getAbsolutePath();
        edtProof.setText(filename);
    }//GEN-LAST:event_btnProofActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnID_Password;
    private javax.swing.JButton btnProof;
    private javax.swing.JButton btnSubmit;
    private javax.swing.JCheckBox ckbFemale;
    private javax.swing.JCheckBox ckbMale;
    private org.jdesktop.swingx.JXDatePicker dDob;
    private javax.swing.JTextField edtID_Passport;
    private java.awt.TextField edtName;
    private javax.swing.JTextField edtProof;
    private java.awt.TextField edtSname;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JProgressBar proBar;
    private javax.swing.JSpinner spnGrade;
    // End of variables declaration//GEN-END:variables
}
