
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.*;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Work
 */
public class AdminTeacherFrm extends javax.swing.JFrame {

    /**
     * Creates new form TeacherFrm
     */
    public AdminTeacherFrm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        edtName = new java.awt.TextField();
        edtSname = new java.awt.TextField();
        spnGrade = new javax.swing.JSpinner();
        btnAdd = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        btnLogins = new javax.swing.JButton();
        edtUname = new java.awt.TextField();
        edtPswd = new java.awt.TextField();
        ckbAdmin = new javax.swing.JCheckBox();
        proBar = new javax.swing.JProgressBar();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setText("Teacher Details");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 20, -1, -1));

        jLabel4.setText("Name:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 70, -1, -1));

        jLabel5.setText("Surname:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 110, -1, -1));

        jLabel6.setText("Grade");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 170, -1, -1));

        jLabel1.setText("Username:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(92, 235, -1, -1));

        jLabel2.setText("Password:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(92, 270, -1, -1));
        getContentPane().add(edtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(206, 64, 100, -1));
        getContentPane().add(edtSname, new org.netbeans.lib.awtextra.AbsoluteConstraints(206, 113, 100, -1));

        spnGrade.setModel(new javax.swing.SpinnerNumberModel(1, 1, 12, 1));
        getContentPane().add(spnGrade, new org.netbeans.lib.awtextra.AbsoluteConstraints(206, 163, 44, -1));

        btnAdd.setText("Add");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });
        getContentPane().add(btnAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 356, 65, -1));

        btnCancel.setText("Cancel");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });
        getContentPane().add(btnCancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(203, 356, -1, -1));

        btnLogins.setText("Generate Logins");
        btnLogins.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginsActionPerformed(evt);
            }
        });
        getContentPane().add(btnLogins, new org.netbeans.lib.awtextra.AbsoluteConstraints(149, 201, -1, -1));
        getContentPane().add(edtUname, new org.netbeans.lib.awtextra.AbsoluteConstraints(203, 235, 100, -1));
        getContentPane().add(edtPswd, new org.netbeans.lib.awtextra.AbsoluteConstraints(203, 265, 100, -1));

        ckbAdmin.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        ckbAdmin.setText("Administration rights");
        ckbAdmin.setContentAreaFilled(false);
        getContentPane().add(ckbAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 295, 148, -1));
        getContentPane().add(proBar, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 325, 148, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Used_chalk_board.jpg"))); // NOI18N
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 400));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnLoginsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginsActionPerformed
        int num = (int) Math.round(Math.random()*100);
        String name = edtName.getText();
        String sname = edtSname.getText();
        String chara = "!@#$^&";
        
        Random random = new Random();
        int index = random.nextInt(chara.length());
        
        edtUname.setText(name.charAt(0) + sname + Integer.toString(num));
        edtPswd.setText((sname + name.charAt(0)).toLowerCase() + Integer.toString(num) + chara.charAt(index));
    }//GEN-LAST:event_btnLoginsActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        boolean valid = true;
        
        //setting name
        String name = edtName.getText();
        if (name.equals(""))
        {
            JOptionPane.showMessageDialog(null, "First name(s) is empty");
            valid = false;
        } else {
            proBar.setValue(proBar.getValue() + 20);
        }
        
        //setting surname
        String sname = edtSname.getText();
        if (sname.equals(""))
        {
            JOptionPane.showMessageDialog(null, "Surname is empty");
            valid = false;
        } else {
            proBar.setValue(proBar.getValue() + 20);
        }
                
        //setting grade
        int grade = (int) spnGrade.getValue();
        proBar.setValue(proBar.getValue() + 20);
        
        //setting username
        String uname = edtUname.getText();
        if (uname.equals(""))
        {
            JOptionPane.showMessageDialog(null, "Username is empty");
            valid = false;
        } else {
            proBar.setValue(proBar.getValue() + 20);
        }
        
        //setting password
        String pswd = edtPswd.getText();
        if (pswd.equals(""))
        {
            JOptionPane.showMessageDialog(null, "Password is empty");
            valid = false;
        } else {
            proBar.setValue(proBar.getValue() + 20);
        }
        
        //if everything is valid, try to save it in the database
        if (valid)
        {
            try {
                Main pro = new Main();
                pro.createConnection();
                
                String sql = "INSERT INTO tblteacher(`Name`, `Surname`, `Grade`, `Username`, `Password`) values (?, ?, ?, ?, ?)";
                PreparedStatement pstmt = Main.con.prepareStatement(sql);
                pstmt.setString(1, name);
                pstmt.setString(2, sname);
                pstmt.setInt(3, grade);
                pstmt.setString(4, uname);
                pstmt.setString(5, pswd);
                
                pstmt.executeUpdate();
                JOptionPane.showMessageDialog(null, "Teacher details successfully recorded");
                
                new AdminDashboard().setVisible(true);
                dispose();
                
                Main.con.close();
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, ex);
            }
        }
        
        if (ckbAdmin.isSelected()) {
            try {
                Main pro = new Main();
                pro.createConnection();

                String Asql = "INSERT INTO tbladmin(`Username`, `Password`) values (?, ?)";
                PreparedStatement Apstmt = Main.con.prepareStatement(Asql);
                Apstmt.setString(1, edtUname.getText());
                Apstmt.setString(2, edtPswd.getText());

                Apstmt.executeUpdate();
                JOptionPane.showMessageDialog(null, "Teacher given adimninistration rights");

                Main.con.close();
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, ex);
            }                                
        }
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        try {
            new AdminDashboard().setVisible(true);
            dispose();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_btnCancelActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnLogins;
    private javax.swing.JCheckBox ckbAdmin;
    private java.awt.TextField edtName;
    private java.awt.TextField edtPswd;
    private java.awt.TextField edtSname;
    private java.awt.TextField edtUname;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JProgressBar proBar;
    private javax.swing.JSpinner spnGrade;
    // End of variables declaration//GEN-END:variables
}
