
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Work
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form AdminLogin
     */
    public Login() {
        initComponents();
    }
    
    public static int ID = -1;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        edtPswd = new javax.swing.JPasswordField();
        edtUname = new java.awt.TextField();
        btnLogin = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        cmbType = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Admin Login");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setText("Login");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 20, -1, -1));

        jLabel3.setText("Username:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, -1, -1));

        jLabel4.setText("Password:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, -1, -1));

        edtPswd.setColumns(10);
        getContentPane().add(edtPswd, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 100, 80, -1));

        edtUname.setColumns(10);
        getContentPane().add(edtUname, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 60, 80, -1));

        btnLogin.setText("Login");
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });
        getContentPane().add(btnLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 83, -1));

        btnCancel.setText("Cancel");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });
        getContentPane().add(btnCancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 180, 83, -1));

        cmbType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "<SELECT>", "Admin", "Parent", "Student", "Teacher" }));
        getContentPane().add(cmbType, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 140, 89, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/school_pencil_border.png"))); // NOI18N
        jLabel1.setAutoscrolls(true);
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 230));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        // getting entered data
        String uname = edtUname.getName();
        String pswd = new String(edtPswd.getPassword());
        String type = cmbType.getSelectedItem().toString();
        
        // testing if data is entered
        if (uname.equals("") || pswd.equals(""))
        {
            JOptionPane.showMessageDialog(null, "Username or password incorrect");
        }
        
        // running accoring to the info selected in the combobox
        switch (type)
        {
            case "<SELECT>": // asks you to check your entered info
                JOptionPane.showMessageDialog(null, "Please select whether your are an administrator, parent, student, teacher");
                break;
            case "Admin": // tests if  logins exist in the admin database
                try {
                    // creating connection
                    Main pro = new Main();
                    pro.createConnection();
                    
                    // executing the query
                    boolean exist = false;
                    String sql = "SELECT AdminID, Username, Password FROM tbladmin"; // gets all records
                    Statement stmt = Main.con.createStatement();
                    ResultSet rs = stmt.executeQuery(sql);
                    rs.beforeFirst();
                    
                    // goes through every record
                    while (rs.next()) {
                    String username = rs.getString("Username");
                    String password =  rs.getString("Password");
                    
                       // searches if entered logins equals the logins in the record
                       if ((uname.equals(username)) || (pswd.equals(password))) {
                            exist = true;
                            ID = rs.getInt("AdminID");
                            // if they equal program goes to admin dashboard form
                            new AdminDashboard().setVisible(true);
                            dispose();
                       }
                    } 
                    
                    // close the execution
                    rs.close();
                    if(!exist){
                           JOptionPane.showMessageDialog(null, "Please Check Username and Password ");
                    } 
                } catch (SQLException ex) {
                    Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
                }
                break;
            case "Parent":
                try {
                    Main pro = new Main();
                    pro.createConnection();
                    
                    boolean exist = false;
                    String sql = "SELECT ParentID, Name, Password FROM tblparent";
                    Statement stmt = Main.con.createStatement();
                    ResultSet rs = stmt.executeQuery(sql);
                    rs.beforeFirst();
                    
                    while (rs.next()) {
                    String username = rs.getString("Name");
                    String password =  rs.getString("Password");
                    
                       if ((uname.equals(username)) || (pswd.equals(password))) {
                            exist = true;
                            ID = rs.getInt("ParentID");
                            new ParentDashboard().setVisible(true);
                            dispose();
                       }
                    } 
                    rs.close();
                    if(!exist){
                           JOptionPane.showMessageDialog(null, "Please Check Username and Password ");
                    } 
                } catch (SQLException ex) {
                    Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
                }
                break;
            case "Student":
                try {
                    Main pro = new Main();
                    pro.createConnection();
                    
                    boolean exist = false;
                    String sql = "SELECT StudentID, Name, Password FROM tblstudent";
                    Statement stmt = Main.con.createStatement();
                    ResultSet rs = stmt.executeQuery(sql);
                    rs.beforeFirst();
                    
                    while (rs.next()) {
                    String username = rs.getString("Name");
                    String password =  rs.getString("Password");
                    
                       if ((uname.equals(username)) || (pswd.equals(password))) {
                            exist = true;
                            ID = rs.getInt("StudentID");
                            new StudentDashboard().setVisible(true);
                            dispose();
                       }
                    } 
                    rs.close();
                    if(!exist){
                           JOptionPane.showMessageDialog(null, "Please Check Username and Password ");
                    }                    
                } catch (SQLException ex) {
                    Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
                }
                break;
            case "Teacher":
                try {
                    Main pro = new Main();
                    pro.createConnection();
                    
                    boolean exist = false;
                    String sql = "SELECT TeacherID, Username, Password FROM tblteacher";
                    Statement stmt = Main.con.createStatement();
                    ResultSet rs = stmt.executeQuery(sql);
                    rs.beforeFirst();
                    
                    while (rs.next()) {
                    String username = rs.getString("Username");
                    String password =  rs.getString("Password");
                    
                       if ((uname.equals(username)) || (pswd.equals(password))) {
                            exist = true;
                            ID = rs.getInt("TeacherID");
                            new TeacherDashboard().setVisible(true);
                            dispose();
                       }
                    } 
                    rs.close();
                    if(!exist){
                           JOptionPane.showMessageDialog(null, "Please Check Username and Password ");
                    } 
                } catch (SQLException ex) {
                    Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
                }
                break;
        }
    }//GEN-LAST:event_btnLoginActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        dispose();
    }//GEN-LAST:event_btnCancelActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnLogin;
    private javax.swing.JComboBox<String> cmbType;
    private javax.swing.JPasswordField edtPswd;
    private java.awt.TextField edtUname;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables
}
